export const abbreviations: Record<"bg" | "en", Record<string, string>> = {
  bg: {
    HPLC: "Високоефективна течна хроматография — метод за точно измерване на чистотата на пептид",
    COA: "Сертификат за анализ (Certificate of Analysis) — документ от независима лаборатория",
    "GLP-1": "Глюкагон-подобен пептид-1 — хормон, регулиращ кръвна захар и апетит",
    BDNF: "Невротрофен фактор от мозъчен произход (Brain-Derived Neurotrophic Factor)",
    "NAD+": "Никотинамид аденин динуклеотид — кофактор, ключов за клетъчния метаболизъм",
    MW: "Молекулна маса (Molecular Weight) — в g/mol",
    CAS: "CAS номер — уникален идентификатор на химическо съединение",
    SKU: "Складов код (Stock Keeping Unit)",
    LOT: "Партиден номер — уникален за всяка производствена партида",
    MFG: "Дата на производство (Manufacturing date)",
    "IGF-1": "Инсулиноподобен растежен фактор-1 (Insulin-like Growth Factor-1)",
    GH: "Растежен хормон (Growth Hormone)",
    HGH: "Човешки растежен хормон (Human Growth Hormone)",
    GHRH: "Хормон, освобождаващ растежен хормон",
    GHRP: "Пептид, освобождаващ растежен хормон",
    MGF: "Механо растежен фактор (Mechano Growth Factor) — сплайс-вариант на IGF-1",
    NNMT: "Никотинамид N-метилтрансфераза — ензим в метаболизма",
    NGF: "Нервен растежен фактор (Nerve Growth Factor)",
    GDNF: "Глиален клетъчно-производен невротрофен фактор",
    PTSD: "Посттравматично стресово разстройство",
    EU: "Европейски съюз",
    ЕС: "Европейски съюз",
    GDPR: "Общ регламент за защита на данните (General Data Protection Regulation)",
    GMP: "Добра производствена практика (Good Manufacturing Practice)",
    FDA: "Агенция по храните и лекарствата на САЩ (Food and Drug Administration)",
    EMA: "Европейска агенция по лекарствата (European Medicines Agency)",
    TLS: "Сигурен транспортен протокол за интернет (Transport Layer Security)",
    DPO: "Длъжностно лице по защита на данните (Data Protection Officer)",
    EET: "Източноевропейско време (GMT+2 зимно / GMT+3 лятно)",
    "PCI DSS": "Стандарт за сигурност на картови данни (Payment Card Industry Data Security Standard)",
    "EU SCC": "Стандартни договорни клаузи на ЕС за трансфер на данни към трети страни",
    Endotoxin: "Бактериален токсин — проверява се с LAL тест в COA",
    "BAC water": "Бактериостатична вода — стерилен разтворител с 0.9% бензилов алкохол",
    LAL: "Лимулус амебоцитен лизат — стандартен тест за ендотоксини",
    PubMed: "Американска медицинска база данни със 35 милиона научни публикации",
    "mRNA": "Информационна РНК — тип нуклеинова киселина",
    ATP: "Аденозин трифосфат — молекула-носител на клетъчна енергия",
    "T3": "Трийодтиронин — активен щитовиден хормон",
    "T4": "Тироксин — хормон на щитовидната жлеза",
    ДДС: "Данък добавена стойност",
    MS: "Масспектрометрия — метод за идентификация на молекули",
  },
  en: {
    HPLC: "High Performance Liquid Chromatography — gold standard for purity analysis",
    COA: "Certificate of Analysis — independent laboratory document",
    "GLP-1": "Glucagon-Like Peptide-1 — blood sugar and appetite hormone",
    BDNF: "Brain-Derived Neurotrophic Factor",
    "NAD+": "Nicotinamide Adenine Dinucleotide — key cellular metabolism cofactor",
    MW: "Molecular Weight (g/mol)",
    CAS: "CAS number — unique chemical compound identifier",
    SKU: "Stock Keeping Unit",
    LOT: "Lot number — unique per production batch",
    MFG: "Manufacturing date",
    "IGF-1": "Insulin-like Growth Factor-1",
    GH: "Growth Hormone",
    HGH: "Human Growth Hormone",
    GHRH: "Growth Hormone-Releasing Hormone",
    GHRP: "Growth Hormone-Releasing Peptide",
    MGF: "Mechano Growth Factor — IGF-1 splice variant",
    NNMT: "Nicotinamide N-Methyltransferase",
    NGF: "Nerve Growth Factor",
    GDNF: "Glial cell-derived neurotrophic factor",
    PTSD: "Post-Traumatic Stress Disorder",
    EU: "European Union",
    GDPR: "General Data Protection Regulation",
    GMP: "Good Manufacturing Practice",
    FDA: "US Food and Drug Administration",
    EMA: "European Medicines Agency",
    TLS: "Transport Layer Security",
    DPO: "Data Protection Officer",
    EET: "Eastern European Time (GMT+2 winter / GMT+3 summer)",
    "PCI DSS": "Payment Card Industry Data Security Standard",
    "EU SCC": "EU Standard Contractual Clauses for third-country data transfer",
    Endotoxin: "Bacterial toxin — verified via LAL test on every COA",
    "BAC water": "Bacteriostatic water — sterile solvent with 0.9% benzyl alcohol",
    LAL: "Limulus Amebocyte Lysate — standard endotoxin test",
    PubMed: "US medical database with 35M scientific publications",
    "mRNA": "Messenger RNA — type of nucleic acid",
    ATP: "Adenosine triphosphate — primary cellular energy molecule",
    "T3": "Triiodothyronine — active thyroid hormone",
    "T4": "Thyroxine — thyroid hormone",
    VAT: "Value Added Tax",
    MS: "Mass Spectrometry — method for molecular identification",
  },
};

export function getAbbreviation(term: string, locale: string): string | null {
  const dict = abbreviations[locale === "bg" ? "bg" : "en"];
  return dict[term] ?? null;
}
